[[main]]
name = "ホーム"
url = ""
weight = 10

[[main]]
name = "メニュー"
url = "menu"
weight = 200
title = "menu"

[[main]]
name = "最新情報"
identifier = "blog"
url = "post"
weight = 40

# [[main]]
# name = "All"
# url = "post"
# weight = 100
# parent = "blog"

# [[main]]
# identifier = "docs"
# name = "Docs"
# url = "page"
# weight = 50

[[social]]
  name = "Instagram"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16"><path d="M8 0C5.25 0 5 0.01 4.05.05c-.95.04-1.6.18-2.17.39a4.38 4.38 0 0 0-1.58 1.05A4.38 4.38 0 0 0 .44 3.92c-.2.57-.35 1.22-.39 2.17C0 5.99 0 6.25 0 9s.01 3 .05 3.95c.04.95.18 1.6.39 2.17a4.38 4.38 0 0 0 1.05 1.58 4.38 4.38 0 0 0 1.58 1.05c.57.2 1.22.35 2.17.39.95.04 1.2.05 3.95.05s3-.01 3.95-.05c.95-.04 1.6-.18 2.17-.39a4.38 4.38 0 0 0 1.58-1.05 4.38 4.38 0 0 0 1.05-1.58c.2-.57.35-1.22.39-2.17.04-.95.05-1.2.05-3.95s-.01-3-.05-3.95c-.04-.95-.18-1.6-.39-2.17a4.38 4.38 0 0 0-1.05-1.58A4.38 4.38 0 0 0 13.08.44c-.57-.2-1.22-.35-2.17-.39C11.01 0 10.75 0 8 0ZM8 1.58c2.74 0 3.05.01 3.94.05.74.03 1.15.15 1.42.25.36.14.62.31.89.59.28.27.45.53.59.89.1.27.22.68.25 1.42.04.89.05 1.2.05 3.94s-.01 3.05-.05 3.94c-.03.74-.15 1.15-.25 1.42a2.8 2.8 0 0 1-.59.89 2.8 2.8 0 0 1-.89.59c-.27.1-.68.22-1.42.25-.89.04-1.2.05-3.94.05s-3.05-.01-3.94-.05c-.74-.03-1.15-.15-1.42-.25a2.8 2.8 0 0 1-.89-.59 2.8 2.8 0 0 1-.59-.89c-.1-.27-.22-.68-.25-1.42-.04-.89-.05-1.2-.05-3.94s.01-3.05.05-3.94c.03-.74.15-1.15.25-1.42.14-.36.31-.62.59-.89a2.8 2.8 0 0 1 .89-.59c.27-.1.68-.22 1.42-.25.89-.04 1.2-.05 3.94-.05Zm0 3.89a3.53 3.53 0 1 0 0 7.06 3.53 3.53 0 0 0 0-7.06Zm0 5.83a2.3 2.3 0 1 1 0-4.59 2.3 2.3 0 0 1 0 4.59Zm4.59-5.98a.83.83 0 1 1-1.66 0 .83.83 0 0 1 1.66 0Z"/></svg>'
  url = "https://www.instagram.com/hair.salon.ryu/"
  weight = 20
  title = "インスタグラム"
